name: build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: wasm-pack-action
              uses: jetli/wasm-pack-action@v0.4.0
            - name: Format code
              run: make pretty
            - name: Build app
              run: make build

